CREATE CONSTRAINT country_id IF NOT EXISTS
FOR (c:Country)
REQUIRE c.id IS UNIQUE;

CREATE CONSTRAINT port_id IF NOT EXISTS
FOR (p:Port)
REQUIRE p.id IS UNIQUE;

CREATE CONSTRAINT supplier_id IF NOT EXISTS
FOR (s:Supplier)
REQUIRE s.id IS UNIQUE;

CREATE CONSTRAINT manufacturer_id IF NOT EXISTS
FOR (m:Manufacturer)
REQUIRE m.id IS UNIQUE;

CREATE CONSTRAINT warehouse_id IF NOT EXISTS
FOR (w:Warehouse)
REQUIRE w.id IS UNIQUE;

CREATE CONSTRAINT product_id IF NOT EXISTS
FOR (p:Product)
REQUIRE p.id IS UNIQUE;

CREATE CONSTRAINT industry_id IF NOT EXISTS
FOR (i:Industry)
REQUIRE i.id IS UNIQUE;